version: '3.8'
# Environment for local development

services:  
  postgres:
    image: postgres:14.5-alpine3.16
    restart: always
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
