version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/frontend-service"
    schedule:
      interval: "monthly"
    target-branch: "main"
    open-pull-requests-limit: 5

  - package-ecosystem: "cargo"
    directory: "/calendar-service"
    schedule:
      interval: "weekly"
    target-branch: "main"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/document-service"
    schedule:
      interval: "weekly"
    target-branch: "main"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/gateway-service"
    schedule:
      interval: "weekly"
    target-branch: "main"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/user-service"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "terraform"
    directory: "/deploy"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
