version: '3.8'

services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: broker-service.Dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      BROKER_PORT: "80"
      USER_GRPC_PORT: "50001"

  user-service:
    build:
      context: ./user-service
      dockerfile: user-service.Dockerfile
    restart: always
    environment:
      GRPC_PORT: "50001"
      MONGODB_NAME: users
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    depends_on:
      - users_mongodb

  users_mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: users
    volumes:
      - ./user-service/db-data/:/data/db/
