version: '3.8'

services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: broker-service.Dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      BROKER_PORT: "80"
      USER_GRPC_PORT: "50001"
      DOCUMENT_GRPC_PORT: "50002"
      CALENDAR_GRPC_PORT: "50051"
    networks:
      - broker-network

  user-service:
    build:
      context: ./user-service
      dockerfile: user-service.Dockerfile
    restart: always
    environment:
      GRPC_PORT: 50001
      POSTGRES_HOST: users_postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
      JWT_SECRET: someSecretJwtKey
    networks:
      - broker-network
      - users-network
    depends_on:
      - users_postgres

  document-service:
    build:
      context: ./document-service
      dockerfile: document-service.Dockerfile
    restart: always
    environment:
      GRPC_PORT: 50002
      POSTGRES_HOST: documents_postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: documents
      ENCRYPTION_KEY: 8dHWTNSAsGaaD7JbqVubF1aWVWGJYF3q
    networks:
      - broker-network
      - documents-network
    depends_on:
      - documents_postgres

  calendar-service:
    build:
      context: ./calendar-service
      dockerfile: calendar-service.Dockerfile
    restart: always
    environment:
      RUST_BACKTRACE: true
      GRPC_PORT: 50051
      ENCRYPTION_KEY: f149VI7P9EsUkirKOnGNy9YKQtbZKEAj
    volumes:
      - ./calendar-service/data/:/data/
    networks:
      - broker-network

  users_postgres:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - ./user-service/db-data/postgres/:/var/lib/postgresql/data
    networks:
      - users-network

  documents_postgres:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: documents
    networks:
      - documents-network
    ports:
      - "5433:5432"
    volumes:
      - ./document-service/db-data/postgres/:/var/lib/postgresql/data

networks:
  broker-network:
  documents-network:
  users-network:
