version: '3.8'
# Environment for local development

services:
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: gateway-service.Dockerfile
    ports:
      - "8080:80"
    environment:
      GATEWAY_PORT: "80"
      USER_GRPC_HOST: "user-service"
      USER_GRPC_PORT: "50001"
      DOCUMENT_GRPC_PORT: "50002"
      DOCUMENT_GRPC_HOST: "document-service"
      CALENDAR_GRPC_PORT: "50051"
      CALENDAR_GRPC_HOST: "calendar-service"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: VWtWRVNWTmZVRUZUVTFkUFVrUQ==
      JWT_SECRET: someSecretJwtKey
      GIN_MODE: debug
      MAILERSEND_API_KEY:
      HOST_URL: http://localhost:8080
      ENVIRONMENT: development
      SENTRY_DSN: 
      HCAPTCHA_SECRET: 0x0000000000000000000000000000000000000000
    networks:
      - gateway-network
      - redis-network
    depends_on:
      - redis

  user-service:
    build:
      context: ./user-service
      dockerfile: user-service.Dockerfile
    environment:
      GRPC_PORT: 50001
      POSTGRES_HOST: users_postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
      SENTRY_DSN: 
    networks:
      - gateway-network
      - users-network
    depends_on:
      - users_postgres

  document-service:
    build:
      context: ./document-service
      dockerfile: document-service.Dockerfile
    environment:
      GRPC_PORT: 50002
      POSTGRES_HOST: documents_postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: documents
      ENCRYPTION_KEY: 8dHWTNSAsGaaD7JbqVubF1aWVWGJYF3q
      SENTRY_DSN:
    networks:
      - gateway-network
      - documents-network
    depends_on:
      - documents_postgres

  calendar-service:
    build:
      context: ./calendar-service
      dockerfile: calendar-service.Dockerfile
    environment:
      RUST_BACKTRACE: true
      GRPC_PORT: 50051
      ENCRYPTION_KEY: f149VI7P9EsUkirKOnGNy9YKQtbZKEAj
    volumes:
      - ./calendar-service/data/:/data/
    networks:
      - gateway-network

  users_postgres:
    image: postgres:14.5-alpine3.16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - ./user-service/db-data/postgres/:/var/lib/postgresql/data
    networks:
      - users-network

  documents_postgres:
    image: postgres:14.5-alpine3.16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: documents
    networks:
      - documents-network
    ports:
      - "5433:5432"
    volumes:
      - ./document-service/db-data/postgres/:/var/lib/postgresql/data
      - ./document-service/db-data/backup/:/backup

  redis:
    image: redis:6.2.7-alpine3.16
    environment:
      REDIS_PASSWORD: VWtWRVNWTmZVRUZUVTFkUFVrUQ==
    entrypoint: ["/bin/sh", "-c", "redis-server --appendonly yes --requirepass $${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru"]
    networks:
      - redis-network
    ports:
      - "6379:6379"
    volumes:
      - ./gateway-service/db-data/redis/:/data

networks:
  gateway-network:
  documents-network:
  users-network:
  redis-network:
