version: '3.8'

services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: broker-service.Dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      BROKER_PORT: "80"
      USER_GRPC_PORT: "50001"
    deploy:
      mode: replicated
      replicas: 1

  user-service:
    build:
      context: ./user-service
      dockerfile: user-service.Dockerfile
    restart: always
    environment:
      GRPC_PORT: "50001"
    deploy:
      mode: replicated
      replicas: 1
