version: '3.8'

services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: broker-service.Dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      BROKER_PORT: "80"
      USER_GRPC_PORT: "50001"
      LOGGER_GRPC_PORT: "50002"
    networks:
      - broker-network

  user-service:
    build:
      context: ./user-service
      dockerfile: user-service.Dockerfile
    restart: always
    environment:
      GRPC_PORT: 50001
      POSTGRES_HOST: users_postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
      JWT_SECRET: someSecretJwtKey
    networks:
      - broker-network
      - users-network
    depends_on:
      - users_postgres
    
  logger-service:
    build:
      context: ./logger-service
      dockerfile: logger-service.Dockerfile
    restart: always
    environment:
      GRPC_PORT: 50002
      MONGODB_NAME: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - broker-network
      - logger-network
    depends_on:
      - logger_mongodb

  document-service:
    build:
      context: ./document-service
      dockerfile: document-service.Dockerfile
    restart: always
    environment:
      GRPC_PORT: 50003
      POSTGRES_HOST: documents_postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: documents
    networks:
      - broker-network
      - documents-network
    depends_on:
      - documents_postgres

  logger_mongodb:
    image: mongo:4.2.21
    ports:
      - "27019:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: users
    networks:
      - logger-network
    volumes:
      - ./logger-service/db-data/mongodb/:/data/db/

  users_postgres:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - ./user-service/db-data/postgres/:/var/lib/postgresql/data
    networks:
      - users-network

  documents_postgres:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: documents
    networks:
      - documents-network
    ports:
      - "5433:5432"
    volumes:
      - ./document-service/db-data/postgres/:/var/lib/postgresql/data

networks:
  broker-network:
  documents-network:
  users-network:
  logger-network:

# TODO 1: create separate networks for each service-db pair and for each broker-service pair!
# TODO 2: remove "expose" and "command" from documents_postgres
