version: '3.8'
# Production environment for web server

services:
  gateway-service:
    image: 'ghcr.io/samgozman/validity.red/gateway-service:latest'
    restart: always
    ports:
      - "8080:80"
    env_file:
      - gateway.env
    networks:
      - redis-network
    depends_on:
      - redis

  redis:
    image: redis:6.2.7-alpine3.16
    restart: always
    env_file:
      - gateway.env
    entrypoint: ["/bin/sh", "-c", "redis-server --appendonly yes --requirepass $${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru"]
    networks:
      - redis-network
    ports:
      - "6379:6379"
    volumes:
      - ./db-data/redis/:/data

networks:
  redis-network:
