#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - snapd
  # Basic nginx dependencies 
  - build-essential
  - libpcre3
  - libpcre3-dev
  - zlib1g
  - zlib1g-dev
  - libssl-dev
  - libgd-dev
  - libxml2
  - libxml2-dev
  - uuid-dev
  # Additional packages that may be needed for nginx modules
  - libossp-uuid-dev
  - libgeoip-dev
  - libxslt-dev
runcmd:
  - ufw disable # disable firewall. Using VPS firewall instead
  - curl -fsSL https://get.docker.com | sh # install docker
  - wget https://nginx.org/download/nginx-1.23.2.tar.gz  # download nginx
  - tar -zxvf nginx-1.23.2.tar.gz # extract nginx
  - cd nginx-1.23.2 # change directory to nginx
  - | # configure nginx
    ./configure \
      --sbin-path=/usr/bin/nginx \
      --conf-path=/etc/nginx/nginx.conf \
      --error-log-path=/var/log/nginx/error.log \
      --http-log-path=/var/log/nginx/access.log \
      --lock-path=/var/lock/nginx.lock \
      --pid-path=/var/run/nginx.pid \
      --with-pcre \
      --with-http_ssl_module \
      --with-http_v2_module 
  - make install
  - | # Add nginx to systemd
    cat >> /lib/systemd/system/nginx.service <<EOL
    [Unit]
    Description=The NGINX HTTP and reverse proxy server
    After=syslog.target network-online.target remote-fs.target nss-lookup.target
    Wants=network-online.target
    [Service]
    Type=forking
    PIDFile=/var/run/nginx.pid
    ExecStartPre=/usr/bin/nginx -t
    ExecStart=/usr/bin/nginx
    ExecReload=/usr/bin/nginx -s reload
    ExecStop=/bin/kill -s QUIT $MAINPID
    PrivateTmp=true
    [Install]
    WantedBy=multi-user.target
    EOL
  - cd .. # get out of nginx directory
  # download temporary nginx config
  - curl -o nginx.conf https://raw.githubusercontent.com/samgozman/validity.red/main/deploy/web/nginx.conf
  - cp -rf nginx.conf /etc/nginx/nginx.conf
  - systemctl start nginx # start nginx
  - systemctl enable nginx # enable nginx on boot
  - mkdir /validityred
  - cd /validityred # Create project folder and copy compose & updater files
  - curl -o docker-compose.yml https://raw.githubusercontent.com/samgozman/validity.red/main/deploy/web/docker-compose.yml
  - curl -o updater.sh https://raw.githubusercontent.com/samgozman/validity.red/main/deploy/updater.sh
  - chmod +x updater.sh
  # Create folder for static files
  - mkdir /srv/validityred
  - mkdir /srv/validityred/files
  # Install certbot
  - snap install core; snap refresh core
  - snap install --classic certbot
  - ln -s /snap/bin/certbot /usr/bin/certbot
  # Create SSL certificate
  - |
    certbot certonly --noninteractive --agree-tos \
      --cert-name validityred \
      -d validity.red -d www.validity.red \
      -m sam@gozman.space \
      --webroot -w /srv/validityred/files
  # Create system cron job to update SSL certificate
  - /bin/bash -c 'echo "0 12 * * * /usr/bin/certbot renew --quiet && systemctl reload nginx" >> /etc/crontab'
  - cd /
  # Download the final nginx config
  - curl -o nginx.conf https://raw.githubusercontent.com/samgozman/validity.red/main/deploy/nginx.conf
  - cp -rf nginx.conf /etc/nginx/nginx.conf
  - systemctl reload nginx # restart nginx
  - reboot
  # TODO: make sure that after reboot, docker-compose up -d is run
