version: '3.8'
# Production environment for Validity.Red

services:
  gateway-service:
    image: 'ghcr.io/samgozman/validity.red/gateway-service:latest'
    ports:
      - "8080:80"
    env_file:
      - ./config/gateway.env
    networks:
      - redis-network
      - users-network
      - documents-network
      - calendars-network
    depends_on:
      - redis

  user-service:
    image: 'ghcr.io/samgozman/validity.red/user-service:latest'
    env_file:
      - ./config/users.env
    ports:
      - "50001:50001"
    networks:
      - users-network
      - postgres-network
    depends_on:
      - postgres

  document-service:
    image: 'ghcr.io/samgozman/validity.red/document-service:latest'
    env_file:
      - ./config/documents.env
    ports:
      - "50002:50002"
    networks:
      - documents-network
      - postgres-network
    depends_on:
      - postgres

  calendar-service:
    image: 'ghcr.io/samgozman/validity.red/calendar-service:latest'
    env_file:
      - ./config/calendars.env
    volumes:
      - ./calendars/data/:/data/
    ports:
      - "50051:50051"
    networks:
      - calendars-network

  postgres:
    image: postgres:14.5-alpine3.16
    env_file:
      - ./config/db.env
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      # Note: Edit path according to your server setup 
      - /mnt/HC_Volume_25024228/db_data:/var/lib/postgresql/data
      # Store temporary backups in the server
      - /backup/:/backup

  redis:
    image: redis:6.2.7-alpine3.16
    env_file:
      - ./config/gateway.env
    entrypoint: ["/bin/sh", "-c", "redis-server --appendonly yes --requirepass $${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru"]
    networks:
      - redis-network
    ports:
      - "6379:6379"
    volumes:
      - ./db-data/redis/:/data

networks:
  gateway-network:
  documents-network:
  calendars-network:
  users-network:
  redis-network:
  postgres-network: