linters:
  enable:
    - gofmt
    - gocyclo
    - bidichk
    - decorder
    - depguard
    - dupword
    - errname
    - errorlint
    - gci
    - godot
    - gomnd
    - gosec
    - makezero
    - misspell
    - nilnil
    - noctx
    - bodyclose
    - prealloc
    - predeclared
    - stylecheck
    - tenv
    - unparam
    - whitespace
    - wsl
    # - tagliatelle

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  gomnd:
    ignored-files:
    - 'main.go'

output:
  format: colored-line-number
  print-issued-lines: false
  print-linter-name: true
