version: '3.8'
# Production environment for web server

services:
  user-service:
    image: 'ghcr.io/samgozman/validity.red/user-service:latest'
    restart: always
    env_file:
      - users.env
    ports:
      - "50001:50001"

  document-service:
    image: 'ghcr.io/samgozman/validity.red/document-service:latest'
    restart: always
    env_file:
      - documents.env
    ports:
      - "50002:50002"

  calendar-service:
    image: 'ghcr.io/samgozman/validity.red/calendar-service:latest'
    restart: always
    env_file:
      - calendars.env
    volumes:
      - ./calendars/data/:/data/
    ports:
      - "50051:50051"

  postgres:
    image: postgres:14.5-alpine3.16
    restart: always
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      # Note: Edit path according to your server setup 
      - /mnt/HC_Volume_25024228/db_data:/var/lib/postgresql/data
