#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3-pip 
write_files:
  - content: |
      0 0 * * * root . /validityred/backup.sh
    path: /etc/crontab
    append: true
runcmd:
  - ufw disable # disable firewall. Using VPS firewall instead
  - pip install b2 # install BackBlaze cli
  - curl -fsSL https://get.docker.com | sh # install docker
  - mkdir /validityred
  - cd /validityred # Create project folder and copy compose & backup.sh files
  - curl -o docker-compose.yml https://raw.githubusercontent.com/samgozman/validity.red/main/deploy/services/docker-compose.yml
  - curl -o backup.sh https://raw.githubusercontent.com/samgozman/validity.red/main/deploy/services/backup.sh
  - chmod +x backup.sh
  - reboot
