name: Backup DB
on:
  workflow_dispatch:

jobs:
  backup-db:
    runs-on: ubuntu-latest
    env:
      SSH_CONNECTION: ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Authenticate server with BackBlaze
        run: ssh $SSH_CONNECTION "
          export B2_APPLICATION_KEY_ID=${{ secrets.B2_APPLICATION_KEY_ID }} &&
          export B2_APPLICATION_KEY=${{ secrets.B2_APPLICATION_KEY }} &&
          b2 authorize-account"

      - name: Run backup script
        run: ssh $SSH_CONNECTION ". /validity/backup.sh"
