name: Build Go images
on:
  workflow_dispatch:

jobs:
  build-and-publish-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Setup protoc
        run: sudo apt install -y protobuf-compiler

      - name: Install protoc-gen-go
        run: >
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          && export PATH="$PATH:$(go env GOPATH)/bin"

      - name: Build proto files
        run: make grpc_init_go

      - name: Build go services
        run: make build_go

      - name: Build gateway-service
        working-directory: ./gateway-service
        run: |
          docker build . -f gateway-service.Dockerfile -t ghcr.io/samgozman/validity.red/gateway-service:latest
          docker push ghcr.io/samgozman/validity.red/gateway-service:latest

      - name: Build user-service
        working-directory: ./user-service
        run: |
          docker build . -f user-service.Dockerfile -t ghcr.io/samgozman/validity.red/user-service:latest
          docker push ghcr.io/samgozman/validity.red/user-service:latest

      - name: Build document-service
        working-directory: ./document-service
        run: |
          docker build . -f document-service.Dockerfile -t ghcr.io/samgozman/validity.red/document-service:latest
          docker push ghcr.io/samgozman/validity.red/document-service:latest

