name: SPA test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }} # Used by sentryVitePlugin to upload source maps
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies (+dev)
        working-directory: ./frontend-service
        run: npm ci

      - name: Build SPA
        working-directory: ./frontend-service
        run: npm run build
