name: Testing validity.red

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build services
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build go services
      run: make build

  unit_test_go:
    name: Run Go unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Test document-service
        working-directory: ./document-service
        run: go test -v ./...

      - name: Test user-service
        working-directory: ./user-service
        run: go test -v ./...

      - name: Test logger-service
        working-directory: ./logger-service
        run: go test -v ./...

      - name: Test broker-service
        working-directory: ./broker-service
        run: go test -v ./...
