name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  unit_test_go:
    name: Go unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Setup protoc
      run: sudo apt install -y protobuf-compiler

    - name: Install protoc-gen-go
      run: >
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        && export PATH="$PATH:$(go env GOPATH)/bin"

    - name: Build proto files
      run: make grpc_init_go

    - name: Build go services
      run: make build_go

    - name: Test document-service
      working-directory: ./document-service
      run: go test -v ./...

    - name: Test user-service
      working-directory: ./user-service
      run: go test -v ./...

    - name: Test gateway-service
      working-directory: ./gateway-service
      run: go test -v ./...

  unit_test_rust:
    name: Rust unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup protoc
      run: sudo apt install -y protobuf-compiler

    - name: Init proto files
      run: make grpc_init_rust

    - name: Build calendar-service
      working-directory: ./calendar-service
      run: cargo build --verbose

    - name: Test calendar-service
      working-directory: ./calendar-service
      run: cargo test --verbose
