name: Testing validity.red

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  unit_test_go:
    name: Build & run Go unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Setup protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'

    - name: Install protoc-gen-go
      run: >
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        && export PATH="$PATH:$(go env GOPATH)/bin"

    - name: Build proto files
      run: make grpc_init_go

    - name: Build go services
      run: make build

    - name: Test document-service
      working-directory: ./document-service
      run: go test -v ./...

    - name: Test user-service
      working-directory: ./user-service
      run: go test -v ./...

    - name: Test gateway-service
      working-directory: ./gateway-service
      run: go test -v ./...

  unit_test_rust:
    name: Build & run Rust unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
